#page title
page_title: RunBuddy
# App Info
ios_app_id: 6738111722 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country: au # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link: # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link: # Enter Google Play Store URL.
presskit_download_link: #
app_icon: # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name: RunBuddy
app_price: # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description: The essential shift diary for Melbourne Train Drivers—stay on track, stay organised.

enable_smart_app_banner: true # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
your_name: Jack Jacobs
your_link: https://emilbaehr.com
your_city: Melbourne, Australia
email_address: jacojac@me.com
facebook_username:
instagram_username: jacojac
twitter_username: jacojac
github_username: jacojac-au
youtube_username:

# Feature List                            Edit, add or remove features to be presented.
features:
  - title: Shifts and Leave Management
    description: "Add shifts and leave, attach slips, and mark any shift as standby or meal-required. Easily clone shifts to other dates for quick updates."
    fontawesome_icon_name: "calendar-check"

  - title: Run Management
    description: "Log your runs in the way you need—times, locations, and anything else relevant to you."
    fontawesome_icon_name: "route"

  - title: Metro Tunnel Support
    description: "Fully compatible with Metro Tunnel operations and test runs."
    fontawesome_icon_name: "train-subway"

  - title: Trip Distance Statistics
    description: "Monitor how far you've driven with detailed insights, automatically excluding non-driving activities like travel time for accurate stats."
    fontawesome_icon_name: "chart-bar"

  - title: Contacts Integration
    description: "Automatically download and create up-to-date work contacts, ensuring you always have the latest information."
    fontawesome_icon_name: "address-book"

  - title: Automatic Backups
    description: "Protect your data with reliable iCloud and local backups, ensuring your records are always safe."
    fontawesome_icon_name: "cloud-upload-alt"

# Theme Settings
topbar_color: "#000000"
topbar_transparency: 0.1
topbar_title_color: "#ffffff"

cover_image: assets/headerimage.png # Replace with alternative image path or image URL.
cover_overlay_color: "#363b3d"
cover_overlay_transparency: 0.8

device_color: black # Set to: blue, black, yellow, coral or white.

body_background_color: "#ffffff"

link_color: "#1d63ea"

app_title_color: "#ffffff"
app_price_color: "#ffffff"
app_description_color: "#ffffff"

feature_title_color: "#000000"
feature_text_color: "#666666"

feature_icons_foreground_color: "#1d63ea"
feature_icons_background_color: "#e6e6e6"

social_icons_foreground_color: "#666666"
social_icons_background_color: "#e6e6e6"

footer_text_color: "#666666"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
