# Page Title
page_title: RunBuddy

# App Info
ios_app_id: 6738111722 # Auto-populates name, price and icons
ios_app_country: au

appstore_link: # Auto-populates if ios_app_id is set
playstore_link:
presskit_download_link: #
app_icon: # assets/appicon.png
app_name: RunBuddy
app_price: # Auto-populates if ios_app_id is set
app_description: "RunBuddy is the diary for Australian train drivers to record shifts, runs, and travel. Plan upcoming work, review past days, and keep everything tidy in one place."

enable_smart_app_banner: true

# Information About Yourself
your_name: Jack Jacobs
your_link: https://emilbaehr.com
your_city: Melbourne, Australia
email_address: jacojac@me.com
facebook_username:
instagram_username: jacojac
twitter_username: jacojac
github_username: jacojac-au
youtube_username:

# Feature List
features:
  - title: Multi-Operator Support
    description: "Switch between operators in-app. Supports Metro Trains Melbourne, V/Line, Sydney Trains, NSW TrainLink, Sydney Metro, and Transperth."
    fontawesome_icon_name: "train"

  - title: Per-Operator Statistics
    description: "Quick filters and detailed insights let you drill into your data by operator, line, or activity."
    fontawesome_icon_name: "chart-pie"

  - title: Shifts and Leave
    description: "Add, clone, set standby and meal requirements, and attach slips or photos. Stay on top of your roster with ease."
    fontawesome_icon_name: "calendar-check"

  - title: Runs
    description: "Record times, locations, notes, and details for every run — flexible logging designed for train drivers."
    fontawesome_icon_name: "route"

  - title: Trip Distance Stats
    description: "Automatically calculates distance driven."
    fontawesome_icon_name: "ruler-combined"

  - title: Backup and Restore
    description: "Keep your records safe with reliable iCloud and local backups — restore anytime with peace of mind."
    fontawesome_icon_name: "cloud-upload-alt"

  - title: Metro Tunnel Support
    description: "Fully compatible with Metro Tunnel operations and future network changes."
    fontawesome_icon_name: "train-subway"
    image: "assets/metro_tunnel_icon.png"

# Theme Settings
topbar_color: "#000000"
topbar_transparency: 0.1
topbar_title_color: "#ffffff"

cover_image: assets/headerimage.png
cover_overlay_color: "#363b3d"
cover_overlay_transparency: 0.8

device_color: black

body_background_color: "#ffffff"

link_color: "#1d63ea"

app_title_color: "#ffffff"
app_price_color: "#ffffff"
app_description_color: "#ffffff"

feature_title_color: "#000000"
feature_text_color: "#666666"

feature_icons_foreground_color: "#1d63ea"
feature_icons_background_color: "#e6e6e6"

social_icons_foreground_color: "#666666"
social_icons_background_color: "#e6e6e6"

footer_text_color: "#666666"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

sass:
  style: :compressed

exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

markdown: kramdown
